/**
 * The only writes public (unauthenticated) code is allowed to perform:
 * inserting a lead or a booking from the /quote, /contact, and /book forms.
 *
 * Callers (`app/actions/leads.ts`, `app/actions/bookings.ts`) run Zod
 * validation + honeypot + rate-limiting first. The DB CHECK constraints on
 * `locale` / `source` / `status` / `service` are the second line of defense
 * (they replace the Supabase anon-insert RLS policy).
 *
 * IDs are generated by the caller (`crypto.randomUUID()`) so the row id is
 * known for the confirmation email without a RETURNING round-trip.
 */

import { db } from "./index";
import { bookings, leads } from "./schema";
import type { BookingInsert, LeadInsert } from "./types";

export async function insertLead(values: LeadInsert): Promise<void> {
  await db.insert(leads).values(values);
}

export async function insertBooking(values: BookingInsert): Promise<void> {
  await db.insert(bookings).values(values);
}
