// AUTO-GENERATED by scripts/optimize-images.ts — do not edit by hand.
// Regenerate with: pnpm run images

export interface OptimizedImage {
  slug: string;
  category: string;
  sourceName: string;
  blurDataURL: string;
  width: number;
  height: number;
  variants: Array<{
    width: number;
    format: "avif" | "webp" | "jpg";
    path: string;
    bytes: number;
  }>;
}

export const IMAGES: OptimizedImage[] = [
  {
    "slug": "custom-engineered-wpc-door",
    "category": "wpc-doors",
    "sourceName": "Custom Engineered WPC Door.png",
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoKAAUABABoJZQCdAEfUBLmAAD7zgHduTJxaTn81OVFZJxMI21AAA==",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/wpc-doors/custom-engineered-wpc-door-640.avif",
        "bytes": 13071
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/wpc-doors/custom-engineered-wpc-door-640.webp",
        "bytes": 17322
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/wpc-doors/custom-engineered-wpc-door-640.jpg",
        "bytes": 26582
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/wpc-doors/custom-engineered-wpc-door-1024.avif",
        "bytes": 24621
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/wpc-doors/custom-engineered-wpc-door-1024.webp",
        "bytes": 33524
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/wpc-doors/custom-engineered-wpc-door-1024.jpg",
        "bytes": 55311
      }
    ]
  },
  {
    "slug": "modern-wpc-interior-door",
    "category": "wpc-doors",
    "sourceName": "Modern WPC Interior Door.png",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoKAAUABABoJYwCdACxo7sAAP33jG/4qtPmOTHh56jysbS5XpX7fdY2AAA=",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/wpc-doors/modern-wpc-interior-door-640.avif",
        "bytes": 15186
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/wpc-doors/modern-wpc-interior-door-640.webp",
        "bytes": 18520
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/wpc-doors/modern-wpc-interior-door-640.jpg",
        "bytes": 28115
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/wpc-doors/modern-wpc-interior-door-1024.avif",
        "bytes": 37969
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/wpc-doors/modern-wpc-interior-door-1024.webp",
        "bytes": 47512
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/wpc-doors/modern-wpc-interior-door-1024.jpg",
        "bytes": 67298
      }
    ]
  },
  {
    "slug": "waterproofbathroom-wpc-door",
    "category": "wpc-doors",
    "sourceName": "WaterproofBathroom WPC Door.png",
    "blurDataURL": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACQAQCdASoKAAUABABoJaQAAlKJUIAA/tb/aC7V1GoSV82k+9AAAA==",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/wpc-doors/waterproofbathroom-wpc-door-640.avif",
        "bytes": 6584
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/wpc-doors/waterproofbathroom-wpc-door-640.webp",
        "bytes": 7254
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/wpc-doors/waterproofbathroom-wpc-door-640.jpg",
        "bytes": 13455
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/wpc-doors/waterproofbathroom-wpc-door-1024.avif",
        "bytes": 13153
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/wpc-doors/waterproofbathroom-wpc-door-1024.webp",
        "bytes": 15574
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/wpc-doors/waterproofbathroom-wpc-door-1024.jpg",
        "bytes": 29422
      }
    ]
  },
  {
    "slug": "concept-5-minimalist-aluminium-entry-door",
    "category": "pivot-aluminium-doors",
    "sourceName": "Concept 5 Minimalist Aluminium Entry Door.png",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAABwAQCdASoKAAUABABoJQAAS3K6wAD+aws8aWV36g81y1SdvJxxu9R6ACe/o3924BQAAAAA",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/pivot-aluminium-doors/concept-5-minimalist-aluminium-entry-door-640.avif",
        "bytes": 16227
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/pivot-aluminium-doors/concept-5-minimalist-aluminium-entry-door-640.webp",
        "bytes": 17780
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/pivot-aluminium-doors/concept-5-minimalist-aluminium-entry-door-640.jpg",
        "bytes": 28927
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/pivot-aluminium-doors/concept-5-minimalist-aluminium-entry-door-1024.avif",
        "bytes": 34161
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/pivot-aluminium-doors/concept-5-minimalist-aluminium-entry-door-1024.webp",
        "bytes": 40562
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/pivot-aluminium-doors/concept-5-minimalist-aluminium-entry-door-1024.jpg",
        "bytes": 64821
      }
    ]
  },
  {
    "slug": "grand-exterior-aluminium-pivot-door",
    "category": "pivot-aluminium-doors",
    "sourceName": "Grand Exterior Aluminium Pivot Door.png",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAUABABoJYgCdAD0mHFksAD+hrDfs9eUwBOTS7xMbBfQMtsGiubiOaNY8pAA",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/pivot-aluminium-doors/grand-exterior-aluminium-pivot-door-640.avif",
        "bytes": 42165
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/pivot-aluminium-doors/grand-exterior-aluminium-pivot-door-640.webp",
        "bytes": 43358
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/pivot-aluminium-doors/grand-exterior-aluminium-pivot-door-640.jpg",
        "bytes": 50586
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/pivot-aluminium-doors/grand-exterior-aluminium-pivot-door-1024.avif",
        "bytes": 94570
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/pivot-aluminium-doors/grand-exterior-aluminium-pivot-door-1024.webp",
        "bytes": 101056
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/pivot-aluminium-doors/grand-exterior-aluminium-pivot-door-1024.jpg",
        "bytes": 115990
      }
    ]
  },
  {
    "slug": "concept-6-glass-and-aluminium-sliding-system",
    "category": "sliding-systems",
    "sourceName": "Concept 6 Glass & Aluminium Sliding System.png",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoKAAUABABoJQBOgBsywWgA/I3776U7ac4KlZorpnvhskbHNy+mAAAA",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/sliding-systems/concept-6-glass-and-aluminium-sliding-system-640.avif",
        "bytes": 16650
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/sliding-systems/concept-6-glass-and-aluminium-sliding-system-640.webp",
        "bytes": 18562
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/sliding-systems/concept-6-glass-and-aluminium-sliding-system-640.jpg",
        "bytes": 30539
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/sliding-systems/concept-6-glass-and-aluminium-sliding-system-1024.avif",
        "bytes": 34623
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/sliding-systems/concept-6-glass-and-aluminium-sliding-system-1024.webp",
        "bytes": 42518
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/sliding-systems/concept-6-glass-and-aluminium-sliding-system-1024.jpg",
        "bytes": 69497
      }
    ]
  },
  {
    "slug": "concept-7-minimalist-pocket-sliding-door",
    "category": "sliding-systems",
    "sourceName": "Concept 7 Minimalist Pocket Sliding Door.png",
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoKAAUABABoJYwCdAD7DivxoAD84oodkx6V6rovWqu3NmQtY0gOycdRlFWBqrTYQ/AAAA==",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/sliding-systems/concept-7-minimalist-pocket-sliding-door-640.avif",
        "bytes": 22922
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/sliding-systems/concept-7-minimalist-pocket-sliding-door-640.webp",
        "bytes": 24652
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/sliding-systems/concept-7-minimalist-pocket-sliding-door-640.jpg",
        "bytes": 34166
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/sliding-systems/concept-7-minimalist-pocket-sliding-door-1024.avif",
        "bytes": 50080
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/sliding-systems/concept-7-minimalist-pocket-sliding-door-1024.webp",
        "bytes": 56580
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/sliding-systems/concept-7-minimalist-pocket-sliding-door-1024.jpg",
        "bytes": 77972
      }
    ]
  },
  {
    "slug": "concept-8-modern-fluted-wall-cladding",
    "category": "wall-cladding",
    "sourceName": "Concept 8 Modern Fluted Wall Cladding.png",
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoKAAUABABoJQBOgCIPY78HDAAA/tIlC/cLkh8zPodAUw+2CsNENDTH2ERVAqs5+kAAAA==",
    "width": 1408,
    "height": 768,
    "variants": [
      {
        "width": 640,
        "format": "avif",
        "path": "/assets/products/wall-cladding/concept-8-modern-fluted-wall-cladding-640.avif",
        "bytes": 20100
      },
      {
        "width": 640,
        "format": "webp",
        "path": "/assets/products/wall-cladding/concept-8-modern-fluted-wall-cladding-640.webp",
        "bytes": 22468
      },
      {
        "width": 640,
        "format": "jpg",
        "path": "/assets/products/wall-cladding/concept-8-modern-fluted-wall-cladding-640.jpg",
        "bytes": 35857
      },
      {
        "width": 1024,
        "format": "avif",
        "path": "/assets/products/wall-cladding/concept-8-modern-fluted-wall-cladding-1024.avif",
        "bytes": 40149
      },
      {
        "width": 1024,
        "format": "webp",
        "path": "/assets/products/wall-cladding/concept-8-modern-fluted-wall-cladding-1024.webp",
        "bytes": 47368
      },
      {
        "width": 1024,
        "format": "jpg",
        "path": "/assets/products/wall-cladding/concept-8-modern-fluted-wall-cladding-1024.jpg",
        "bytes": 81939
      }
    ]
  }
] as const;

/** Convenience lookup: get an image by category slug + image slug */
export function findImage(category: string, slug: string): OptimizedImage | undefined {
  return IMAGES.find((img) => img.category === category && img.slug === slug);
}

/** All images in a category */
export function imagesByCategory(category: string): OptimizedImage[] {
  return IMAGES.filter((img) => img.category === category);
}

/** For <Image src=...> — picks the best (widest) JPG fallback */
export function bestJpg(img: OptimizedImage): string | undefined {
  const jpg = img.variants.filter((v) => v.format === "jpg").sort((a, b) => b.width - a.width)[0];
  return jpg?.path;
}
