/**
 * Seed product catalog — used by the homepage category grid (Prompt 3),
 * the product detail pages (Prompt 4), and the quote form context
 * (Prompt 5). Moves to Supabase in Prompt 7 with the same shape (bilingual
 * `_en` / `_ar` columns and an array of image paths).
 *
 * Each product references the optimized image manifest generated by
 * `scripts/optimize-images.ts` (see `lib/image-manifest.ts`) — that way
 * we never hard-code paths and always use the responsive variants.
 */

import { findImage, type OptimizedImage } from "./image-manifest";

export type ProductCategorySlug =
  | "wpc-doors"
  | "pivot-aluminium-doors"
  | "sliding-systems"
  | "wall-cladding";

export interface Product {
  slug: string;
  category: ProductCategorySlug;
  /** Translation keys live in messages/{en,ar}.json under `products.items` (added in Prompt 4). */
  name_en: string;
  name_ar: string;
  description_en: string;
  description_ar: string;
  /** Resolved at module load time so callers don't have to handle undefined. */
  image: OptimizedImage;
  /** Used to sort/feature products on the homepage. */
  featured?: boolean;
  /** AED minimum, displayed as "from AED X" — null when "by quote only". */
  priceFromAed?: number;
}

/** Build a product row from manifest, throwing if the image went missing. */
function product(
  slug: string,
  category: ProductCategorySlug,
  imageSlug: string,
  data: Omit<Product, "slug" | "category" | "image">,
): Product {
  const image = findImage(category, imageSlug);
  if (!image) {
    throw new Error(
      `Product "${slug}" references missing image "${category}/${imageSlug}". ` +
        `Run \`pnpm run images\` to regenerate the manifest.`,
    );
  }
  return { slug, category, image, ...data };
}

export const PRODUCTS: Product[] = [
  // ── WPC Doors ────────────────────────────────────────────────────────────
  product("modern-wpc-interior", "wpc-doors", "modern-wpc-interior-door", {
    name_en: "Modern WPC Interior Door",
    name_ar: "باب WPC داخلي حديث",
    description_en:
      "Slim, contemporary interior door in light oak veneer. Engineered Wood Plastic Composite resists humidity, sound, and wear — ideal for villas and apartments alike.",
    description_ar:
      "باب داخلي رفيع وحديث بقشرة بلوط فاتح. خشب بلاستيك مركب مهندس يقاوم الرطوبة والصوت والاهتراء — مثالي للفلل والشقق على حد سواء.",
    featured: true,
  }),
  product("waterproof-bathroom-wpc", "wpc-doors", "waterproofbathroom-wpc-door", {
    name_en: "Waterproof Bathroom WPC Door",
    name_ar: "باب حمام WPC مقاوم للماء",
    description_en:
      "Designed for wet zones: full waterproof core, sealed edges, and a finish that resists warping over a decade of daily use.",
    description_ar:
      "مصمم للمناطق الرطبة: نواة مقاومة للماء بالكامل، حواف محكمة الإغلاق، وتشطيب يقاوم الالتواء لعشر سنوات من الاستخدام اليومي.",
  }),
  product("custom-engineered-wpc", "wpc-doors", "custom-engineered-wpc-door", {
    name_en: "Custom Engineered WPC Door",
    name_ar: "باب WPC هندسي مخصص",
    description_en:
      "Built to your dimensions and panel design. Choose finish, hardware, and glazing — manufactured in our UAE factory in days, not weeks.",
    description_ar:
      "مصنوع وفق أبعادك وتصميمك للألواح. اختر التشطيب والإكسسوارات والزجاج — يُصنع في مصنعنا في الإمارات خلال أيام، لا أسابيع.",
  }),

  // ── Pivot Aluminium Doors ────────────────────────────────────────────────
  product(
    "grand-exterior-pivot",
    "pivot-aluminium-doors",
    "grand-exterior-aluminium-pivot-door",
    {
      name_en: "Grand Exterior Aluminium Pivot Door",
      name_ar: "باب محوري ألمنيوم خارجي فخم",
      description_en:
        "A statement entryway: oversized aluminium pivot with a single sculptural pull handle. Engineered for villa scale and humid UAE conditions.",
      description_ar:
        "مدخل يلفت الأنظار: باب محوري ألمنيوم بحجم كبير مع مقبض سحب نحتي واحد. مصمم لحجم الفلل والظروف الرطبة في الإمارات.",
      featured: true,
    },
  ),
  product(
    "minimalist-aluminium-entry",
    "pivot-aluminium-doors",
    "concept-5-minimalist-aluminium-entry-door",
    {
      name_en: "Minimalist Aluminium Entry Door",
      name_ar: "باب مدخل ألمنيوم بسيط",
      description_en:
        "A restrained pivot design — flush profiles, hidden hinges, and a powder-coat palette tuned to UAE light and dust.",
      description_ar:
        "تصميم محوري متحفظ — ملامح مسطحة، مفصلات مخفية، ولوحة طلاء بودرة مضبوطة للضوء والغبار الإماراتي.",
    },
  ),

  // ── Sliding Systems ─────────────────────────────────────────────────────
  product(
    "glass-aluminium-sliding",
    "sliding-systems",
    "concept-6-glass-and-aluminium-sliding-system",
    {
      name_en: "Glass & Aluminium Sliding System",
      name_ar: "نظام منزلق زجاج وألمنيوم",
      description_en:
        "Floor-to-ceiling glass panels in a slim aluminium frame. Defines spaces without closing them off — perfect for open-plan apartments.",
      description_ar:
        "ألواح زجاجية من الأرض إلى السقف في إطار ألمنيوم رفيع. يحدد المساحات دون عزلها — مثالي للشقق المفتوحة.",
      featured: true,
    },
  ),
  product(
    "minimalist-pocket-sliding",
    "sliding-systems",
    "concept-7-minimalist-pocket-sliding-door",
    {
      name_en: "Minimalist Pocket Sliding Door",
      name_ar: "باب منزلق جيب بسيط",
      description_en:
        "A door that disappears when not in use. Pocket-style with soft-close and a low-profile track flush with the floor.",
      description_ar:
        "باب يختفي عند عدم الاستخدام. نمط جيب مع إغلاق ناعم ومسار منخفض الارتفاع مدمج مع الأرضية.",
    },
  ),

  // ── Wall Cladding ──────────────────────────────────────────────────────
  product(
    "modern-fluted-cladding",
    "wall-cladding",
    "concept-8-modern-fluted-wall-cladding",
    {
      name_en: "Modern Fluted Wall Cladding",
      name_ar: "كسوة جدران محززة حديثة",
      description_en:
        "Vertical fluted panels in walnut or oak. Adds rhythm and warmth to feature walls without overwhelming the room.",
      description_ar:
        "ألواح محززة عمودية بخشب الجوز أو البلوط. تضيف إيقاعًا ودفئًا للجدران المميزة دون إثقال الغرفة.",
      featured: true,
    },
  ),
];

/** Helper: featured products for the homepage category grid. */
export function featuredByCategory(): Record<ProductCategorySlug, Product | undefined> {
  return {
    "wpc-doors": PRODUCTS.find((p) => p.category === "wpc-doors" && p.featured),
    "pivot-aluminium-doors": PRODUCTS.find(
      (p) => p.category === "pivot-aluminium-doors" && p.featured,
    ),
    "sliding-systems": PRODUCTS.find(
      (p) => p.category === "sliding-systems" && p.featured,
    ),
    "wall-cladding": PRODUCTS.find(
      (p) => p.category === "wall-cladding" && p.featured,
    ),
  };
}

/** Helper: all products in a category, used by the catalog pages (Prompt 4). */
export function productsByCategory(category: ProductCategorySlug): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

/**
 * Picks the bilingual field for the active locale.
 * Falls back to English if the Arabic value is empty (defensive — should
 * never happen but means a missed translation doesn't crash the page).
 */
export function localized<T extends string>(
  enValue: T,
  arValue: T,
  locale: string,
): T {
  if (locale === "ar" && arValue) return arValue;
  return enValue;
}
