/**
 * Hand-written TypeScript types matching the Supabase schema in
 * `supabase/migrations/0001_initial_schema.sql`.
 *
 * Why hand-written instead of generated by `supabase gen types`?
 * The CLI requires Docker for the local dev DB, which we opted out of
 * (chose paste-SQL workflow in Prompt 7). Since we author the schema
 * ourselves, the types can match exactly with no codegen step.
 *
 * Keep this file in lockstep with the SQL — if you change a column,
 * update both the migration and this file.
 *
 * The `Database` type is the generic the Supabase client uses to type
 * all `.from()` / `.select()` / `.insert()` / `.update()` calls.
 */

// ── ENUM-like string unions (mirror SQL CHECK constraints) ─────────────────

export type ProductCategory =
  | "wpc-doors"
  | "pivot-aluminium-doors"
  | "sliding-systems"
  | "wall-cladding";

export type ProjectCategory = "residential" | "commercial" | "luxury";

export type Locale = "en" | "ar";

export type LeadSource = "quote" | "contact" | "product-page";
export type LeadStatus = "new" | "contacted" | "converted" | "lost";

export type BookingService =
  | "consultation"
  | "installation"
  | "technician"
  | "custom";
export type BookingStatus =
  | "new"
  | "confirmed"
  | "in_progress"
  | "completed"
  | "cancelled";

export type TechnicianStatus = "active" | "inactive" | "on_leave";

export type SiteSettingType = "text" | "image" | "video" | "json";

// ── Database type for Supabase client generic ──────────────────────────────

export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          slug: string;
          name_en: string;
          name_ar: string;
          category: ProductCategory;
          category_en: string;
          category_ar: string;
          description_en: string;
          description_ar: string;
          price_from_aed: number | null;
          images: string[];
          is_featured: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name_en: string;
          name_ar: string;
          category: ProductCategory;
          category_en: string;
          category_ar: string;
          description_en: string;
          description_ar: string;
          price_from_aed?: number | null;
          images?: string[];
          is_featured?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          slug?: string;
          name_en?: string;
          name_ar?: string;
          category?: ProductCategory;
          category_en?: string;
          category_ar?: string;
          description_en?: string;
          description_ar?: string;
          price_from_aed?: number | null;
          images?: string[];
          is_featured?: boolean;
          is_active?: boolean;
        };
        Relationships: [];
      };

      projects: {
        Row: {
          id: string;
          slug: string;
          category: ProjectCategory;
          title_en: string;
          title_ar: string;
          location_en: string;
          location_ar: string;
          description_en: string;
          description_ar: string;
          images: string[];
          tags: string[];
          is_published: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          category: ProjectCategory;
          title_en: string;
          title_ar: string;
          location_en: string;
          location_ar: string;
          description_en: string;
          description_ar: string;
          images?: string[];
          tags?: string[];
          is_published?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["projects"]["Insert"]>;
        Relationships: [];
      };

      leads: {
        Row: {
          id: string;
          name: string;
          email: string | null;
          phone: string;
          subject: string | null;
          product: string | null;
          quantity: string | null;
          location: string | null;
          budget: string | null;
          message: string;
          locale: Locale;
          source: LeadSource;
          status: LeadStatus;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email?: string | null;
          phone: string;
          subject?: string | null;
          product?: string | null;
          quantity?: string | null;
          location?: string | null;
          budget?: string | null;
          message: string;
          locale?: Locale;
          source?: LeadSource;
          status?: LeadStatus;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["leads"]["Insert"]>;
        Relationships: [];
      };

      bookings: {
        Row: {
          id: string;
          customer_name: string;
          phone: string;
          email: string | null;
          service: BookingService;
          area: string;
          preferred_date: string; // ISO date string "YYYY-MM-DD"
          preferred_time_slot: string | null;
          duration_minutes: number | null;
          notes: string | null;
          locale: Locale;
          status: BookingStatus;
          assigned_technician: string | null;
          admin_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_name: string;
          phone: string;
          email?: string | null;
          service: BookingService;
          area: string;
          preferred_date: string;
          preferred_time_slot?: string | null;
          duration_minutes?: number | null;
          notes?: string | null;
          locale?: Locale;
          status?: BookingStatus;
          assigned_technician?: string | null;
          admin_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["bookings"]["Insert"]>;
        Relationships: [
          {
            foreignKeyName: "bookings_assigned_technician_fkey";
            columns: ["assigned_technician"];
            referencedRelation: "technicians";
            referencedColumns: ["id"];
          },
        ];
      };

      technicians: {
        Row: {
          id: string;
          name: string;
          phone: string;
          email: string | null;
          skills: string[];
          hourly_rate_aed: number | null;
          availability: Record<string, unknown> | null;
          status: TechnicianStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          email?: string | null;
          skills?: string[];
          hourly_rate_aed?: number | null;
          availability?: Record<string, unknown> | null;
          status?: TechnicianStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["technicians"]["Insert"]>;
        Relationships: [];
      };

      site_settings: {
        Row: {
          key: string;
          value_en: string | null;
          value_ar: string | null;
          value_json: Record<string, unknown> | null;
          type: SiteSettingType;
          description: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value_en?: string | null;
          value_ar?: string | null;
          value_json?: Record<string, unknown> | null;
          type?: SiteSettingType;
          description?: string | null;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["site_settings"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// ── Convenience aliases for table rows ─────────────────────────────────────

export type ProductRow = Database["public"]["Tables"]["products"]["Row"];
export type ProjectRow = Database["public"]["Tables"]["projects"]["Row"];
export type LeadRow = Database["public"]["Tables"]["leads"]["Row"];
export type LeadInsert = Database["public"]["Tables"]["leads"]["Insert"];
export type BookingRow = Database["public"]["Tables"]["bookings"]["Row"];
export type BookingInsert = Database["public"]["Tables"]["bookings"]["Insert"];
export type TechnicianRow = Database["public"]["Tables"]["technicians"]["Row"];
export type SiteSettingRow = Database["public"]["Tables"]["site_settings"]["Row"];
